import { v4 as uuidv4 } from "uuid";
function data() {
  return [
    //TOP 10
    {
      name: "Seven Nation Army",
      cover: "covers/seven_nation_army.jpg",
      artist: "The white Stripes",
      audio: "audio/01 - Seven Nation Army (Album Version).mp3",
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: true,
    },

    {
      name: "Paradise",
      cover: "covers/full_of_stars.jpg",
      artist: "Coldplay",
      audio: "audio/Coldplay - Paradise .mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Viva La Vida",
      cover: "covers/full_of_stars.jpg",
      artist: "Coldplay",
      audio: "audio/Coldplay - Viva La Vida .mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "A Sky Full Of STARS",
      cover: "covers/full_of_stars.jpg",
      artist: "Coldplay",
      audio: "audio/Coldplay - A Sky Full of Stars .mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "A head Full Of Dreams",
      cover: "covers/full_of_stars.jpg",
      artist: "Coldplay",
      audio: "audio/Coldplay - A Head Full Of Dreams .mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },

    {
      name: "No Hay nadie Como tu",
      cover: "covers/tacuba.jpg",
      artist: "Calle 13",
      audio:
        "audio/Calle 13 - No Hay Nadie Como Tú (Audio) ft. Café Tacuba.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },

    {
      name: "Bajo El Agua",
      cover: "covers/medrano.jpg",
      artist: "Manuel Medrano",
      audio: "audio/Manuel Medrano - Bajo El Agua (Video Oficial).mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },

    {
      name: "You're Beautiful",
      cover: "covers/james_blunt.jpg",
      artist: "James Blunt",
      audio: "audio/You re Beautiful - James Blunt 🎵.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },

    {
      name: "Up & Up",
      cover: "covers/full_of_stars.jpg",
      artist: "Coldplay",
      audio: "audio/Coldplay - Up&Up (Official Video).mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },

    //Daft PUNK
    {
      name: "Give Life Back To Music",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/01 Give Life Back To Music.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "The Game of Love",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/02 The Game of Love.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Giorgio by Moroder",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/03 Giorgio by Moroder.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Within",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/04 Within.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Instant Crush",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/05 Instant Crush.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Lose Yourself To Dance",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/06 Lose Yourself To Dance.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Touch",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/07 Touch.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Get Lucky",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/08 Get Lucky.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Beyond",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/09 Beyond.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Motherboard",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/10 Motherboard.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Fragments of Time",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/11 Fragments of Time.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Doin'it Right",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/12 Doin'it Right.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Contact",
      cover:
        "https://ia801909.us.archive.org/7/items/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5/mbid-79215cdf-4764-4dee-b0b9-fec1643df7c5-25581939208.jpg",
      artist: "Daft Punk",
      audio: "audio/13 Contact.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    //harry styles}
    {
      name: " Golden",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/01. Golden.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Watermelon Sugar",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/02. Watermelon Sugar.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Adore You",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/03. Adore You.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Lights Up",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/04. Lights Up.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Cherry",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/05. Cherry.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Falling",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/06. Falling.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " To Be So Lonely",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/07. To Be So Lonely.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " She",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/08. She.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Sunflower, Vol. 6",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/09. Sunflower, Vol. 6.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Canyon Moon",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/10. Canyon Moon.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Treat People With Kindness",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/11. Treat People With Kindness.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Fine Line",
      cover: "https://m.media-amazon.com/images/I/61uPLHJ4nPL._SS500_.jpg",
      artist: "Harry Styles",
      audio: "audio/12. Fine Line.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Wake Me Up",
      cover:
        "https://images-na.ssl-images-amazon.com/images/I/61kS5HJqLDL._SL1200_.jpg",
      artist: "Avicii",
      audio: "http://www.musci.rf.gd/01%20Wake%20Me%20Up.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "You Make Me",
      cover:
        "https://images-na.ssl-images-amazon.com/images/I/61kS5HJqLDL._SL1200_.jpg",
      artist: "Avicii",
      audio: "http://www.musci.rf.gd/02%20You%20Make%20Me.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Hey Brother",
      cover:
        "https://images-na.ssl-images-amazon.com/images/I/61kS5HJqLDL._SL1200_.jpg",
      artist: "Avicii",
      audio: "http://www.musci.rf.gd/03%20Hey%20Brother.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Addicted To You",
      cover:
        "https://images-na.ssl-images-amazon.com/images/I/61kS5HJqLDL._SL1200_.jpg",
      artist: "Avicii",
      audio: "http://www.musci.rf.gd/04%20Addicted%20To%20You.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Liar Liar",
      cover:
        "https://images-na.ssl-images-amazon.com/images/I/61kS5HJqLDL._SL1200_.jpg",
      artist: "Avicii",
      audio: "http://www.musci.rf.gd/06%20Liar%20Liar.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Shame On Me",
      cover:
        "https://images-na.ssl-images-amazon.com/images/I/61kS5HJqLDL._SL1200_.jpg",
      artist: "Avicii",
      audio: "http://www.musci.rf.gd/07%20Shame%20On%20Me.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Long Road To Hell",
      cover:
        "https://images-na.ssl-images-amazon.com/images/I/61kS5HJqLDL._SL1200_.jpg",
      artist: "Avicii",
      audio: "http://www.musci.rf.gd/11%20Long%20Road%20To%20Hell.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Enter Sandman",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/01.%20Enter%20Sandman.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Master Of Puppets",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/01.%20Master%20Of%20Puppets.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " That Was Just Your Life",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/01.%20That%20Was%20Just%20Your%20Life.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The End Of The Line",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/01.%20The%20End%20Of%20The%20Line.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Battery",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/02.%20Battery.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Holier Than Thou",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/02.%20Holier%20Than%20Thou.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " I Disappear",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/02.%20I%20Disappear.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " It's Electric",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/02.%20It's%20Electric.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Fuel",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/03.%20Fuel.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Harvester Of Sorrow",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/03.%20Harvester%20Of%20Sorrow.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Nothing Else Matters",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/03.%20Nothing%20Else%20Matters.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The Memory Remains",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/03.%20The%20Memory%20Remains.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " One",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/04.%20One.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The Day That Never Comes",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/04.%20The%20Day%20That%20Never%20Comes.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The Unforgiven III",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/04.%20The%20Unforgiven%20III.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The Unforgiven",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/04.%20The%20Unforgiven.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Hero Of The Day",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/05.%20Hero%20Of%20The%20Day.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The Thing That Should Not Be",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/05.%20The%20Thing%20That%20Should%20Not%20Be.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Until It Sleeps",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/05.%20Until%20It%20Sleeps.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Wherever I May Roam",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/05.%20Wherever%20I%20May%20Roam.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Of Wolf And Man",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/06.%20Of%20Wolf%20And%20Man.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Sabbra Cadabra",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/06.%20Sabbra%20Cadabra.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Welcome Home (Sanitarium)",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/06.%20Welcome%20Home%20(Sanitarium).mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Whiskey In The Jar",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/06.%20Whiskey%20In%20The%20Jar.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Better Than You",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/07.%20Better%20Than%20You.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Creeping Death",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/07.%20Creeping%20Death.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Sad But True",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/07.%20Sad%20But%20True.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The Unforgiven II",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/07.%20The%20Unforgiven%20II.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Die Die My Darling",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/08.%20Die%20Die%20My%20Darling.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Fade To Black",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/08.%20Fade%20To%20Black.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " King Nothing",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/08.%20King%20Nothing.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Through The Never",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/08.%20Through%20The%20Never.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " ... And Justice For All",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/09.%20...%20And%20Justice%20For%20All.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Blackened",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/09.%20Blackened.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Broken Beat And Scarred",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/09.%20Broken%20Beat%20And%20Scarred.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Cyanide",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/09.%20Cyanide.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Don't Tread Оn Me",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/10.%20Don't%20Tread%20Оn%20Me.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Jump In The Fire",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/10.%20Jump%20In%20The%20Fire.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Loverman",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/10.%20Loverman.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Turn The Page",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/10.%20Turn%20The%20Page.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Ain't My Bitch",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/11.%20Ain't%20My%20Bitch.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Ride The Lightning",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/11.%20Ride%20The%20Lightning.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Some Kind Of Monster",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/11.%20Some%20Kind%20Of%20Monster.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " The Four Horsemen",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/11.%20The%20Four%20Horsemen.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " 1 X 4",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/12.%201%20X%204.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " For Whom The Bell Tolls",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio:
        "http://www.musci.rf.gd/metalica/12.%20For%20Whom%20The%20Bell%20Tolls.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Frantic",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/12.%20Frantic.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Hit The Lights",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/12.%20Hit%20The%20Lights.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Devil's Dance",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/13.%20Devil's%20Dance.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Mama Said",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/13.%20Mama%20Said.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Orion",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/13.%20Orion.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Seek And Destroy",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/13.%20Seek%20And%20Destroy.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " Human",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/14.%20Human.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: " No Leaf Clover",
      cover: "https://m.media-amazon.com/images/I/51RN3UGAJ1L._SS500_.jpg",
      artist: "Metallica",
      audio: "http://www.musci.rf.gd/metalica/14.%20No%20Leaf%20Clover.mp3",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
  ];
}

export default data;
